// This is a Javascript test harness that simulates the execution of Lambda function code

var MyLambdaFunction = require('../src/index.js'); // assumes single Lambda function with exports.handler

 // this is the Lambda request data, generated by the Alexa service.  Replace with your actual Alexa request.
var event =
    {
  "session": {
    "sessionId": "SessionId.0e1be074-8116-423a-82fe-c44ea94da848",
    "application": {
      "applicationId": "amzn1.ask.skill.6093d16e-5fcb-4a58-a9ce-bcb4df244cd0"
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.account.AHKED6V2EVSMLJ4DQYKXRTUFGG4QYWGSQGFAMJH253XUX6PJ7DNEZBZOPPNKBY3JLF7EJU5UB2ZLXIDMTJWP5JTC4OKBJIY44KPBWPLNXNMNXA6PQBVNDGIJCK4Q2T62DT2CIWZC5EFEKKF2L3KIACZC2SYG3RECBM3SUTYVQQBMLRY5P2DWR4JFAPMZIB4PJVAHMILSKIONAQI",
      "accessToken": "Atza|IwEBILBMYqjCDRa3PfF30LDtHjNpT4vTSdnW7oTaCkzo5YHCEUWicVP_UHQTgmce3Mht-OE4TB1Ok8uYtWzWxMtM3EyQLR_iFrKCHNJshGQAUhU_1GO52PgB0eJD6vO7eQ_4VZSvBNkrg-rzxdwIVqsm7Diek1XgKliEIOS_D1I3arTmxmBES2Tu0aYrboFmc9PH5YoBoJXEomyFza-McAhrXiP_tjybvF0cfo4UhE7PQiel1IPoD6sfkWoIyKdzYs6fPpXm8qXJYya2ebhTig8Bd5Z9d-w3eo_UGpE_mVTu6k8bJqh9hGTHmBPOhDVIjGv319I6IHRnB6CqeQLWv2zvFd4VEE_npApBhh9Fxtgrbim7U1EAOgw6URoEIjSX99J19ueJiu_f3N6friRiTvXTMNsJJg-l9yJ4PU4bt4SYlNSPiIjQGFt2qToqT3TZVsRi3MsrwjtX0IC0s0DLIR0qb-0tQAntStAFUwQA1wgUSjKNLZvrhrIoAqpUoIuWBoj0538"
    },
    "new": true
  }
  "version": "1.0"
}

var context = {
    'succeed': function (data) {
        console.log(JSON.stringify(data, null,'\t') );

    },
    'fail': function (err) {
        console.log('context.fail occurred');
        console.log(JSON.stringify(err, null,'\t') );
    }

};

function callback(error, data) {
    if(error) {
        console.log('error: ' + error);
    } else {
        console.log(data);
    }
}

// call the function
MyLambdaFunction['handler'] (event, context, callback);
